name: Deploy GKE Swarm (Google Cloud)
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: swarm-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v2
      - name: Deploy GKE Autopilot
        run: |
          gcloud container clusters create-auto aave-swarm-v6-2 \
            --region=northamerica-northeast2 \
            --enable-autopilot \
            --spot \
            --release-channel=regular \
            --machine-type=n1-standard-4
      - name: Build & Deploy Swarm Agents
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/swarm-agents .
          kubectl apply -f k8s/
