name: Deploy GKE Swarm
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: swarm-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com
      - uses: google-github-actions/setup-gcloud@v2
      - run: |
          gcloud container clusters create-auto aave-swarm-v6-2 \
            --region=northamerica-northeast2 \
            --enable-autopilot \
            --spot \
            --release-channel=regular
          # GPU Spot ready via pod requests
